@echo off

SET BASE_PATH=%~dp0
SET PLUGIN_DIR_PATH=%BASE_PATH:~0,-1%
SET PLUGIN_CODE_DIR_PATH=%PLUGIN_DIR_PATH%\code
SET PLUGIN_CODE_PATH=%PLUGIN_CODE_DIR_PATH%\dist\screendeck.exe

"%PLUGIN_CODE_PATH%" %*
